stages:
  - build
  - deploy
.default: &DEFAULT
  tags: [ cluster ]

.build: &BUILD
  <<: *DEFAULT
  tags: [ cluster ]
  stage: build
  script:
    - pacman -Syy
    - echo 'Server = https://mirror.fsrv.services/pub/archlinux/$repo/os/$arch' > /etc/pacman.d/mirrorlist
    - pacman -Syy --noconfirm go
    - go build -o hetzner-dnsapi-client_${GOOS}-${GOARCH} main.go
  image: archlinux
  artifacts:
    paths:
      - hetzner-dnsapi-client_${GOOS}-${GOARCH}

amd64:openbsd:
  <<: *BUILD
  variables:
    GOARCH: amd64
    GOOS: openbsd
amd64:freebsd:
  <<: *BUILD
  variables:
    GOARCH: amd64
    GOOS: freebsd
amd64:linux:
  <<: *BUILD
  variables:
    GOARCH: amd64
    GOOS: linux

